Repository artsy/palette-mobile, pull requests merged in 2023-04, with the labels that each got.

#78 chore(migration): Add missing eigen palette stuff
  .storybook/storybook.requires.js
  package.json
  src/elements/Autocomplete/Autocomplete.tests.tsx
  src/elements/Avatar/Avatar.tests.tsx
  src/elements/BackButton/BackButton.tsx
  src/elements/Checkbox/Check.tsx
  src/elements/Checkbox/Checkbox.stories.tsx
  src/elements/Checkbox/Checkbox.tsx
  src/elements/Checkbox/index.tsx
  src/elements/CollapsibleMenuItem/CollapsibleMenuItem.stories.tsx
  src/elements/Dialog/Dialog.stories.tsx
  src/elements/Dialog/Dialog.tests.tsx
  src/elements/Dialog/Dialog.tsx
  src/elements/Dialog/index.ts
  src/elements/Message/Message.stories.tsx
  src/elements/Message/Message.tests.tsx
  src/elements/Message/Message.tsx
  src/elements/Message/index.tsx
  src/elements/index.tsx
  yarn.lock
Labels: Version: Minor

#79 fix(migration): fix missing migration items
  src/elements/Avatar/Avatar.tsx
  src/elements/Checkbox/Checkbox.tsx
Labels: Version: Minor

#80 fix: replace spacerprops with flexprops
  src/elements/EntityHeader/EntityHeader.tsx
Labels: Version: Minor

#81 chore(scripts): rename yarn local-palette-dev
  package.json
Labels: Version: Minor

#82 chore(migration): Move more shared stuff over
  src/elements/Input/Input.stories.tsx
  src/elements/Input/Input.tests.tsx
  src/elements/Input/Input.tsx
  src/elements/List/List.stories.tsx
  src/elements/ProgressBar/ProgressBar.stories.tsx
  src/elements/ProgressBar/ProgressBar.tests.tsx
  src/elements/ProgressBar/ProgressBar.tsx
  src/elements/ToolTip/ToolTip.stories.tsx
  src/elements/ToolTip/ToolTip.tests.tsx
  src/elements/ToolTip/ToolTip.tsx
  src/elements/ToolTip/ToolTipFlyout.tsx
  src/elements/ToolTip/index.ts
  src/elements/Touchable/Touchable.tsx
  src/elements/VisualClue/VisualClue.stories.tsx
  src/elements/VisualClue/VisualClueDot.tsx
  src/elements/VisualClue/VisualClueText.tsx
  src/elements/index.tsx
Labels: Version: Minor

#84 ci(circle): Add CircleCI support
  .circleci/config.yml
  .github/workflows/publish-canary.yml
  .github/workflows/release.yml
Labels: Version: Patch

#85 docs(dev): Update README with notes on yalc
  README.md
Labels: Version: Minor, patch

#87 fix: reanimated button crash fix
  src/elements/Button/Button.tsx
Labels: Version: Minor

#88 fix(button): fix worklet crash error in eigen
  src/elements/Button/Button.tsx
Labels: Version: Patch

#89 feat(progress-bar): Add `animationDuration` prop
  src/elements/ProgressBar/ProgressBar.tsx
Labels: Version: Minor

#90 feat: add `EmptyCheckCircleIcon`
  src/svgs/EmptyCheckCircleIcon.tsx
  src/svgs/index.tsx
Labels: Version: Minor

#92 build(deps): followup on rn upgrade
  Gemfile
  Gemfile.lock
  package.json
Labels: Version: Minor
