Repository artsy/palette-mobile, pull requests merged in 2023-08, with the labels that each got.

#120 feat(Image): enable more styling on the Image element and more
  src/elements/Image/Image.stories.tsx
  src/elements/Image/Image.tsx
Labels: Version: Minor

#132 feat: bump reanimated 3
  babel.config.js
  ios/Podfile.lock
  package.json
  src/elements/ButtonNew/Button.tsx
  src/elements/Pill/Pill.tsx
  src/elements/ProgressBar/ProgressBar.tsx
  src/elements/Screen/ScreenFlatList.tsx
  src/elements/Screen/hooks/useAnimatedHeaderScrolling.tsx
  src/elements/Screen/hooks/useListenForScreenScroll.tsx
  src/elements/Skeleton/Skeleton.tsx
  src/elements/Tabs/SubTabBar.tsx
  src/elements/ToolTip/ToolTipFlyout.tsx
  yarn.lock
Labels: Jira Synced, Version: Major

#134 fix(Pill): remove animation from MotiPressable
  src/elements/Pill/Pill.tsx
Labels: Version: Minor

#135 fix(Pill): animate moti using worklet
  src/elements/Pill/Pill.tsx
Labels: Version: Minor

#137 feat(Popover): add Popover element
  .storybook/storybook.requires.js
  package.json
  src/elements/Popover/Popover.stories.tsx
  src/elements/Popover/Popover.tsx
  src/elements/Popover/index.tsx
  src/elements/index.tsx
  yarn.lock
Labels: Version: Minor

#136 chore(palette-tokens): bump palette-tokens to v5
  package.json
  src/tokens.ts
  src/types.ts
  src/utils/hooks/useTheme.tsx
  src/utils/webTokensToMobile.ts
  yarn.lock
Labels: major, Version: Major

#133 feat: add Tabs.Masonry and bump react-native-collapsible-tab-view from 6.1.4 to 6.2.0
  package.json
  yarn.lock
Labels: canary, Version: Minor

#139 feat: Add xOffset prop to ToolTip
  src/elements/ToolTip/ToolTip.tsx
Labels: Jira Synced, Version: Minor

#140 feat: Add onPress to ToolTip
  src/elements/ToolTip/ToolTip.tsx
Labels: Jira Synced, Version: Minor

#141 feat(Popover): add background color
  src/elements/Popover/Popover.tsx
Labels: Version: Minor

#138 feat: masonry
  ios/Podfile.lock
  package.json
  src/elements/Tabs/TabMasonry.tsx
  src/elements/Tabs/Tabs.ts
  yarn.lock
Labels: Jira Synced, canary, major

#143 feat(Tabs): add pointerEvents none to tabsWithHeader title
  src/elements/Tabs/Tabs.stories.tsx
  src/elements/Tabs/TabsWithHeader.tsx
Labels: Version: Minor

#144 feat(TabsWithHeader): show BelowTitleHeaderComponent if we don't display the title
  src/elements/Tabs/Tabs.stories.tsx
  src/elements/Tabs/TabsWithHeader.tsx
Labels: Version: Minor
