Repository artsy/palette-mobile, pull requests merged in 2023-01, with the labels that each got.

#34 feat: add surface colors
  .eslintrc.js
  .storybook/Storybook.tsx
  .storybook/preview.js
  .storybook/storybook.requires.js
  ios/Podfile.lock
  lib/colors.stories.tsx
  lib/elements/Input/Input.stories.tsx
  lib/elements/Input/Input.tsx
  lib/elements/Radio/RadioButton.tsx
  lib/elements/Separator/Separator.stories.tsx
  lib/elements/Separator/Separator.tsx
  lib/tokens.ts
  package.json
  src/storybook/decorators.tsx
  yarn.lock
Labels: minor, release, canary

#36 tools: remeda -> lodash
  lib/Theme.tsx
  lib/elements/Input/Input.tsx
  lib/elements/Tabs/TabBarContainer.tsx
  lib/tokens.ts
  package.json
  yarn.lock
Labels: patch, release, canary

#33 feat(skeleton): Add skeleton loading states
  .storybook/storybook.requires.js
  .vscode/settings.json
  lib/atoms/BackButton/BackButton.tsx
  lib/constants.ts
  lib/elements/Skeleton/Skeleton.stories.tsx
  lib/elements/Skeleton/Skeleton.tsx
  lib/elements/Skeleton/index.tsx
  lib/elements/index.tsx
  lib/index.ts
  package.json
Labels: release, Version: Minor, Jira Synced, canary

#37 fix: imports
  lib/elements/Skeleton/Skeleton.stories.tsx
Labels: patch, release

#38 upgrade RN and move some deps around
  .gitignore
  README.md
  android/app/build.gradle
  android/app/src/main/jni/Android.mk
  android/app/src/main/jni/CMakeLists.txt
  android/app/src/main/jni/MainApplicationModuleProvider.cpp
  android/app/src/main/jni/MainApplicationModuleProvider.h
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  android/app/src/main/jni/MainComponentsRegistry.cpp
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  ios/.xcode.env
  ios/PaletteMobile.xcodeproj/project.pbxproj
  ios/Podfile
  ios/Podfile.lock
  lib/utils/MeasuredView.tsx
  lib/utils/useScreenDimensions.tsx
  package.json
  src/App.tsx
  yarn.lock
Labels: release, major, canary

#41 feat: remove images
  lib/elements/Banner/Banner.tsx
  lib/images/close-x.webp
  lib/images/close-x@2x.webp
  lib/images/close-x@3x.webp
  lib/images/package.json
Labels: release, major, Version: Minor, canary
