Repository artsy/palette-mobile, pull requests merged in 2023-10, with the labels that each got.

#159 chore: support flatlist ref
  src/elements/Tabs/TabMasonry.tsx
Labels: Version: Minor

#160 fix: make innerRef optional
  src/elements/Tabs/TabMasonry.tsx
Labels: squashongreen, Version: Minor

#161 feat(DIA-134): add ImageSetIcon
  src/svgs/ImageSetIcon.tsx
  src/svgs/index.tsx
Labels: Jira Synced, Version: Minor
