Repository artsy/palette-mobile, pull requests merged in 2023-09, with the labels that each got.

#145 chore: support icon positioning in Message component
  src/elements/Message/Message.tsx
Labels: Jira Synced, squashongreen, Version: Minor

#146 chore: add build status on circle ci
  README.md
Labels: Version: Minor

#147 feat(tabs): adds scroll offsets to the tabs when checking scroll position
  src/elements/Screen/Header.tsx
  src/elements/Screen/ScreenScrollContext.tsx
  src/elements/Screen/hooks/useAnimatedHeaderScrolling.tsx
  src/elements/Screen/hooks/useListenForScreenScroll.tsx
  src/elements/Tabs/hooks/useListenForTabContentScroll.tsx
Labels: Version: Minor

#148 feat(Image): expose gemini resize mode from Image
  src/elements/Image/Image.tsx
  src/utils/createGeminiUrl.ts
Labels: Version: Minor

#149 fix(image): set default Gemini resize mode to `fill`
  src/utils/createGeminiUrl.ts
Labels: Jira Synced, Version: Minor

#150 docs: update readme with Developing Features using Local Versions
  README.md
Labels: Version: Minor

#151 fix: Add flowDirection prop to tooltip component
  src/elements/ToolTip/ToolTip.tsx
Labels: Version: Minor

#153 fix: progressive onboarding positioning on android
  src/elements/Popover/Popover.tsx
Labels: Jira Synced, Version: Minor

#152 feat: change port to avoid conflict with Eigen
  ios/PaletteMobile.xcodeproj/project.pbxproj
  package.json
Labels: Version: Minor

#155 feat(DIA-110): remove artist variant and replaces with profile on Pill element
  src/elements/Pill/Pill.stories.tsx
  src/elements/Pill/Pill.tsx
Labels: Jira Synced, Version: Minor

#156 feat(Pill): adjust horizontal padding of profile variant
  src/elements/Pill/Pill.tsx
Labels: Version: Minor

#158 feat(Pill): adjusts the image overflow for profile variant
  src/elements/Pill/Pill.tsx
Labels: Version: Minor
