Repository artsy/palette-mobile, pull requests merged in 2023-11, with the labels that each got.

#164 feat(checkbox): expose custom accessibilityProps to the View wrapping the icon
  src/elements/Checkbox/Checkbox.tsx
Labels: Version: Minor

#165 fix: specify compatible kotlin version to avoid dup class error
  android/build.gradle
Labels: Version: Minor

#163 Fix(ONYX-508): Fix vertical centering of text within pills
  src/elements/Pill/Pill.tsx
Labels: Jira Synced, Version: Trivial

#167 fix: patch upgrade for rn ios build issue, fix port not being respected
  Gemfile
  Gemfile.lock
  ios/Podfile
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Version: Minor, FF

#168 ci: add iOS and Android basic ci check
  .circleci/config.yml
Labels: Version: Minor, FF

#169 feat: support dotted pill
  src/elements/Pill/Pill.stories.tsx
  src/elements/Pill/Pill.tsx
Labels: Jira Synced, squashongreen, Version: Minor

#170 chore: update gray shade of dotted pill
  src/elements/Pill/Pill.tsx
Labels: Version: Minor
