Repository artsy/palette-mobile, pull requests merged in 2023-06, with the labels that each got.

#104 feat(tabs): Add Tabs component
  package.json
  src/elements/LegacyTabs/ContentTabs.tsx
  src/elements/LegacyTabs/NavigationalTabs.tsx
  src/elements/LegacyTabs/StepTabs.tsx
  src/elements/LegacyTabs/Tab.tsx
  src/elements/LegacyTabs/TabBarContainer.tsx
  src/elements/LegacyTabs/index.tsx
  src/elements/Screen/Header.tsx
  src/elements/Screen/index.tsx
  src/elements/Tabs/SubTabBar.tsx
  src/elements/Tabs/TabFlatList.tsx
  src/elements/Tabs/TabScrollView.tsx
  src/elements/Tabs/Tabs.ts
  src/elements/Tabs/TabsContainer.tsx
  src/elements/Tabs/TabsContext.tsx
  src/elements/Tabs/TabsWithHeader.tsx
  src/elements/Tabs/index.ts
  src/elements/Tabs/useListenForTabContentScroll.tsx
  src/elements/index.tsx
  yarn.lock
Labels: Version: Minor

#105 fix(header): make text more configurable
  src/elements/Screen/Header.tsx
Labels: Version: Patch

#106 fix(header): Make expand
  src/elements/Screen/Header.tsx
Labels: Version: Patch

#107 fix(tabs): Ensure title content is properly centered
  src/elements/Screen/Header.tsx
  src/elements/Tabs/TabsContainer.tsx
Labels: Version: Patch, Jira Synced

#109 feat(tabs): Add support for Indicators
  .storybook/storybook.requires.js
  Gemfile
  ios/Podfile.lock
  src/elements/Tabs/Tabs.stories.tsx
  src/elements/Tabs/TabsContainer.tsx
Labels: Version: Minor, Jira Synced

#110 fix(touchable): underlayColor replace white100 to transparent
  src/elements/Touchable/Touchable.tsx
Labels: Version: Minor, Jira Synced

#111 refactor: adjust tab header animation
  src/elements/Screen/Header.tsx
Labels: Version: Minor, Jira Synced

#114 feat(screen): Add scroll tracking support for animated headers
  .storybook/storybook.requires.js
  docs/pull_request_template.md
  src/elements/Screen/Header.tsx
  src/elements/Screen/Screen.stories.tsx
  src/elements/Screen/ScreenBase.tsx
  src/elements/Screen/ScreenFlatList.tsx
  src/elements/Screen/ScreenScrollContext.tsx
  src/elements/Screen/ScreenScrollView.tsx
  src/elements/Screen/hooks/useAnimatedHeaderScrolling.tsx
  src/elements/Screen/hooks/useListenForScreenScroll.tsx
  src/elements/Screen/index.tsx
  src/elements/Tabs/TabFlatList.tsx
  src/elements/Tabs/TabScrollView.tsx
  src/elements/Tabs/Tabs.stories.tsx
  src/elements/Tabs/Tabs.ts
  src/elements/Tabs/TabsContext.tsx
  src/elements/Tabs/TabsWithHeader.tsx
  src/elements/Tabs/hooks/useListenForTabContentScroll.tsx
  src/storybook/decorators.tsx
Labels: Version: Major, Jira Synced

#115 fix(screen): fix centering on non-animated title
  src/elements/Screen/Header.tsx
Labels: patch

#116 feat(screen): Make FloatingHeader more customizable
  src/elements/Screen/FloatingHeader.tsx
Labels: release, minor

#117 feat(image): Add new <Image> component
  .storybook/storybook.requires.js
  ios/Podfile.lock
  package.json
  src/elements/Image/Image.stories.tsx
  src/elements/Image/Image.tsx
  src/elements/Image/index.tsx
  src/elements/index.tsx
  src/storybook/decorators.tsx
  src/utils/createGeminiUrl.ts
  yarn.lock
Labels: release, minor, Version: Minor

#118 fix: indicator on android is not visible
  src/elements/Tabs/TabsContainer.tsx
Labels: Version: Minor

#119 feat(CX-3748): Add private icon to Entity Header
  .storybook/storybook.requires.js
  src/elements/EntityHeader/EntityHeader.stories.tsx
  src/elements/EntityHeader/EntityHeader.tsx
Labels: Jira Synced, Version: Minor
