Repository artsy/palette-mobile, pull requests merged in 2023-02, with the labels that each got.

#44 feat: add more text things from eigen
  lib/helpers/text.ts
Labels: minor, release

#45 fix: some index files
  lib/index.ts
Labels: patch, release

#46 icons: added some, removed aliases
  lib/elements/Banner/Banner.tsx
  lib/elements/Header/ArtsyLogoHeader.tsx
  lib/svgs/ArtsyLogoBlackIcon.tsx
  lib/svgs/ArtsyMarkBlackIcon.tsx
  lib/svgs/CheckCircleFillIcon.tsx
  lib/svgs/CheckCircleIcon.tsx
  lib/svgs/CloseCircleFillIcon.tsx
  lib/svgs/CloseCircleIcon.tsx
  lib/svgs/EstablishedIcon.tsx
  lib/svgs/EyeClosedIcon.tsx
  lib/svgs/EyeOpenedIcon.tsx
  lib/svgs/GuaranteeIcon.tsx
  lib/svgs/ImageIcon.tsx
  lib/svgs/InstitutionIcon.tsx
  lib/svgs/MapPinIcon.tsx
  lib/svgs/Payment2Icon.tsx
  lib/svgs/QuestionCircleIcon.tsx
  lib/svgs/SecureLockIcon.tsx
  lib/svgs/StarCircleIcon.tsx
  lib/svgs/Tag2Icon.tsx
  lib/svgs/UserMultiIcon.tsx
  lib/svgs/UserSingleIcon.tsx
  lib/svgs/index.tsx
Labels: release, major, Version: Major

#47 chore: just a version bump
  lib/hooks.ts
Labels: release, major, canary

#48 feat: export two icons
  lib/svgs/index.tsx
Labels: minor, release, Version: Minor

#49 feat: remove react-spring, and replace it with reanimated
  .github/workflows/publish-canary.yml
  .github/workflows/release.yml
  .gitignore
  .storybook/storybook.requires.js
  .tool-versions
  babel.config.js
  index.js
  ios/Podfile.lock
  jest.config.js
  lib/Theme.tsx
  lib/elements/Button/Button.stories.tsx
  lib/elements/Button/Button.tests.tsx
  lib/elements/Button/Button.tsx
  lib/elements/Button/colors.tsx
  lib/elements/Button/index.tsx
  lib/elements/Collapse/Collapse.stories.tsx
  lib/elements/Collapse/Collapse.tsx
  lib/elements/CollapsibleMenuItem/CollapsibleMenuItem.tsx
  lib/elements/Text/Text.tsx
  lib/hooks.ts
  lib/setupJest.ts
  lib/tokens.ts
  lib/utils/tests/renderWithWrappers.tsx
  package.json
  tsconfig.json
  yarn.lock
Labels: release, prerelease, major, Version: Minor, canary

#50 docs: add darkmode docs and remove tslint comments
  docs/migrations/dark-mode.md
  lib/Theme.tsx
  lib/elements/Touchable/TouchableWithScale.tsx
  lib/tokens.ts
  screenshots/dark-mode.png
  screenshots/light-mode.png
Labels: Version: Minor

#52 fix: Button was missing the restProps
  lib/elements/Button/Button.tsx
  lib/elements/Button/colors.tsx
Labels: minor, release, Version: Minor

#53 feat: typescript magic, allowing negative DS values, and 0 and auto
  lib/tokens.ts
  package.json
  yarn.lock
Labels: Version: Minor, canary

#54 fix: Flex can now have ref without type errors
  .storybook/storybook.requires.js
  lib/atoms/Box/Box.stories.tsx
  lib/atoms/Flex/Flex.tsx
  lib/elements/CollapsibleMenuItem/CollapsibleMenuItem.tsx
  lib/space.stories.tsx
  package.json
Labels: release, Version: Minor, squashongreen

#55 fix: button spacing
  .storybook/storybook.requires.js
  lib/elements/Button/Button.stories.tsx
  lib/elements/Button/Button.tsx
  src/App.tsx
Labels: release, Version: Minor

#56 Add MoneyCircleIcon and WorldGlobeCircleIcon
  lib/svgs/MoneyCircleIcon.tsx
  lib/svgs/WorldGlobeCircleIcon.tsx
  lib/svgs/index.tsx
Labels: release, Version: Minor, squashongreen

#58 fix: remove displaynames
  lib/atoms/Box/Box.tsx
  lib/atoms/Flex/Flex.tsx
  lib/atoms/Spacer/Spacer.tsx
  lib/elements/Button/colors.ts
  lib/elements/EntityHeader/EntityHeader.tsx
  lib/elements/Input/Input.tsx
Labels: Version: Minor

#59 feat: less confusing name for darkmode support
  lib/Theme.tsx
  lib/hooks.ts
  lib/tokens.ts
  src/storybook/decorators.tsx
Labels: Version: Major

#60 fix: button block and animations
  lib/elements/Button/Button.stories.tsx
  lib/elements/Button/Button.tsx
  lib/utils/MeasuredView.tsx
Labels: Version: Minor, major

#63 fix: export types
  lib/index.ts
Labels: patch

#64 feat(toolchain): Add `yarn sync-after-change` for local dev publishing
  package.json
  scripts/sync-after-change
  yarn.lock
Labels: internal, Version: Trivial

#65 feat(toolchain): Add lint staged commit checks
  .husky/pre-commit
  .husky/pre-push
  package.json
  yarn.lock
Labels: internal

#66 fix: removing sc from radiodot
  lib/elements/Radio/RadioDot.tsx
Labels: Version: Minor, patch

#67 fix: provider error and text prep
  .storybook/storybook.requires.js
  lib/Theme.tsx
  lib/elements/Button/Button.tests.tsx
  lib/elements/Text/LinkText.tsx
  lib/elements/Text/Text.stories.tsx
  lib/elements/Text/Text.tests.ts
  lib/elements/Text/Text.tsx
  lib/svgs/Icon.tsx
  lib/utils/hooks/useTheme.tsx
Labels: Version: Minor, patch

#68 feat: OMG TYPES FOR STYLED COMPONENTS? FINALLY AND YES PLEASE!
  lib/elements/Text/Text.stories.tsx
  lib/elements/Text/Text.tsx
Labels: Version: Minor, patch

#70 feat: add hitslop on button
  src/elements/Button/Button.tsx
Labels: Version: Minor

#71 fix: some eslint issues
  .eslintrc.js
  ios/Podfile.lock
  package.json
  src/elements/ArtsyKeyboardAvoidingView/ArtsyKeyboardAvoidingView.tsx
  src/elements/Avatar/Avatar.stories.tsx
  src/elements/Avatar/Avatar.tsx
  src/elements/BackButton/BackButton.stories.tsx
  src/elements/Banner/Banner.tsx
  src/elements/BorderBox/BorderBox.tsx
  src/elements/Button/Button.stories.tsx
  src/elements/Button/Button.tsx
  src/elements/Button/colors.ts
  src/elements/Checkbox/Checkbox.stories.tsx
  src/elements/Checkbox/Checkbox.tsx
  src/elements/CollapsibleMenuItem/CollapsibleMenuItem.tsx
  src/elements/EntityHeader/EntityHeader.tsx
  src/elements/Input/Input.stories.tsx
  src/elements/Input/Input.tsx
  src/elements/MenuItem/MenuItem.tsx
  src/elements/Radio/RadioButton.tsx
  src/elements/Radio/RadioDot.tsx
  src/elements/SearchInput/SearchInput.tsx
  src/elements/Separator/Separator.stories.tsx
  src/elements/Skeleton/Skeleton.stories.tsx
  src/elements/Skeleton/Skeleton.tsx
  src/elements/Spacer/Spacer.stories.tsx
  src/elements/Spinner/Spinner.tsx
  src/elements/Tabs/NavigationalTabs.tsx
  src/elements/Tabs/StepTabs.tsx
  src/elements/Tabs/TabBarContainer.tsx
  src/elements/Text/Text.tsx
  src/elements/Touchable/Touchable.stories.tsx
  src/elements/Touchable/Touchable.tsx
  src/elements/Touchable/TouchableHighlightColor.tsx
  src/elements/VisualClue/VisualClueDot.tsx
  src/elements/VisualClue/VisualClueText.tsx
  src/storybook/decorators.tsx
  src/svgs/AddCircleFillIcon.tsx
  src/svgs/ArrowCircleFillIcons.tsx
  src/svgs/BoltCircleFill.tsx
  src/svgs/CloseCircleFillIcon.tsx
  src/svgs/GuaranteeIcon.tsx
  src/svgs/ImageIcon.tsx
  src/svgs/MagnifyingGlassIcon.tsx
  src/svgs/Payment2Icon.tsx
  src/svgs/SecureLockIcon.tsx
  src/svgs/ShieldIcon.tsx
  src/svgs/StarCircleFill.tsx
  src/svgs/StarCircleIcon.tsx
  src/svgs/Tag2Icon.tsx
  src/svgs/TriangleDown.tsx
  src/svgs/WhatsAppAppIcon.tsx
  src/svgs/icons.stories.tsx
  src/utils/colors.stories.tsx
  src/utils/hooks/useTheme.tsx
  src/utils/space.stories.tsx
  src/utils/tests/renderWithWrappers.tsx
  src/utils/types.ts
  src/utils/webTokensToMobile.ts
  yarn.lock
Labels: patch
