Repository artsy/palette-mobile, pull requests merged in 2024-03, with the labels that each got.

#198 fix: Update onChange prop in Switch
  src/elements/Switch/Switch.stories.tsx
  src/elements/Switch/Switch.tsx
Labels: Version: Minor

#201 fix: make sure image comes on top of the skeleton
  src/elements/Image/Image.tsx
Labels: Version: Minor

#204 fix: progressbar crash in dev and broken in prod
  src/elements/ProgressBar/ProgressBar.tsx
Labels: Jira Synced, Version: Minor

#205 feat: add onboarding state in pills
  src/elements/Pill/Pill.stories.tsx
  src/elements/Pill/Pill.tsx
Labels: Jira Synced, Version: Minor

#206 fix(radio): fix alignment between button and text
  .storybook/storybook.requires.js
  src/elements/Radio/RadioButton.stories.tsx
  src/elements/Radio/RadioButton.tsx
Labels: Jira Synced, Version: Minor

#208 feat: Add `preventUnmount` prop to `CollapsibleMenuItem`
  src/elements/Collapse/Collapse.tsx
Labels: Jira Synced, Version: Minor, Squash On Green
