Repository artsy/palette-mobile, pull requests merged in 2024-07, with the labels that each got.

#243 feat(Button): respect variant style given loading state
  .storybook/storybook.requires.js
  src/elements/Button/Button.stories.tsx
  src/elements/Button/Button.tsx
  src/elements/ButtonNew/Button.stories.tsx
Labels: Version: Minor

#245 feat(Message): makes title optional
  src/elements/Message/Message.stories.tsx
  src/elements/Message/Message.tsx
Labels: Jira Synced, Version: Minor

#244 feat: add select/copy support to text fields by default
  src/elements/Text/Text.tsx
Labels: Version: Minor

#246 fix: multiline input scrolling
  src/elements/Input/Input.tests.tsx
  src/elements/Input/Input.tsx
Labels: Version: Minor

#247 feat: add tab.flashlist support
  src/elements/Tabs/TabFlashList.tsx
  src/elements/Tabs/Tabs.ts
Labels: canary, Version: Minor

#248 build(deps): bump collapsible-tab-view
  package.json
  yarn.lock
Labels: Version: Minor, hack14
