Repository artsy/palette-mobile, pull requests merged in 2024-11, with the labels that each got.

#275 feat: add new heart and follow icons
  src/svgs/FollowArtistFillIcon.tsx
  src/svgs/FollowArtistIcon.tsx
  src/svgs/NewFillHeartIcon.tsx
  src/svgs/NewHeartIcon.tsx
  src/svgs/index.tsx
Labels: Jira Synced, Version: Minor

#277 feat(DIA-937): add apple and google icons
  src/svgs/AppleIcon.tsx
  src/svgs/FacebookIcon.tsx
  src/svgs/GoogleIcon.tsx
  src/svgs/index.tsx
Labels: Jira Synced, Version: Minor

#269 build(deps): bump react-native from 0.73.10 to 0.75.4
  .gitignore
  Gemfile
  Gemfile.lock
  android/app/build.gradle
  android/app/src/main/java/com/palettemobile/MainApplication.kt
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle
  app/App.tsx
  ios/PaletteMobile.xcodeproj/project.pbxproj
  ios/PaletteMobile/AppDelegate.mm
  ios/PaletteMobile/Info.plist
  ios/Podfile
  ios/Podfile.lock
  jest.config.js
  metro.config.js
  package.json
  patches/react-native-collapsible-tab-view+8.0.0.patch
  src/elements/Screen/ScreenFlatList.tsx
  src/setupJest.ts
  yarn.lock
Labels: canary, major, Version: Major

#278 feat: add RoundSearchInput component
  src/elements/SearchInput/RoundSearchInput.tsx
  src/elements/SearchInput/index.ts
  src/svgs/ArrowLeftIcon.tsx
Labels: Jira Synced, canary, squashongreen, Version: Minor

#283 chore: remove layout animation from round search input
  src/elements/SearchInput/RoundSearchInput.tsx
Labels: Version: Minor, Squash On Green

#281 chore: allow using uncontrolled inputs
  src/elements/Input/Input.tests.tsx
  src/elements/Input/Input.tsx
Labels: Version: Minor

#284 refactor: proper use of useSharedValue
  .eslintrc.js
  package.json
  src/elements/Avatar/Avatar.tsx
  src/elements/ButtonNew/Button.tests.tsx
  src/elements/ButtonNew/Button.tsx
  src/elements/Dialog/Dialog.tests.tsx
  src/elements/Image/Image.tsx
  src/elements/Input/Input.tests.tsx
  src/elements/Input/Input.tsx
  src/elements/Message/Message.tests.tsx
  src/elements/Pill/Pill.tests.tsx
  src/elements/ProgressBar/ProgressBar.tsx
  src/elements/Screen/hooks/useAnimatedHeaderScrolling.tsx
  src/elements/Screen/hooks/useListenForScreenScroll.tsx
  src/elements/Skeleton/Skeleton.tsx
  src/elements/ToolTip/ToolTip.tests.tsx
  src/elements/ToolTip/ToolTipFlyout.tsx
  src/setupJest.ts
  yarn.lock
Labels: Jira Synced, Version: Minor

#285 chore: fix test failures and warnings from last upgrade
  src/elements/Input/Input.tsx
  src/elements/Screen/hooks/useAnimatedHeaderScrolling.tsx
Labels: canary, Version: Minor, Squash On Green

#287 chore: increase hitslop of search icon
  src/elements/SearchInput/RoundSearchInput.tsx
Labels: Version: Minor, Squash On Green

#288 feat: add button loading spinner testid
  src/elements/Button/Button.tsx
Labels: Version: Minor

#289 chore: revert "add button loading spinner testid"
  src/elements/Button/Button.tsx
Labels: Version: Minor
