Repository artsy/palette-mobile, pull requests merged in 2024-10, with the labels that each got.

#264 feat(Chip): add chip element
  .storybook/storybook.requires.js
  src/elements/Chip/Chip.stories.tsx
  src/elements/Chip/Chip.tsx
  src/elements/Chip/index.ts
  src/elements/index.tsx
Labels: Jira Synced, Version: Minor

#266 fix: sticky sub header padding
  src/elements/Screen/StickySubHeader.tsx
Labels: Version: Minor

#267 build(deps): bump react-native from 0.73.9 to 0.73.10
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Version: Minor

#274 feat(gap): use our spacing tokens with gap prop
  src/elements/Box/Box.stories.tsx
  src/elements/Box/Box.tsx
  src/elements/Chip/Chip.stories.tsx
  src/elements/Radio/RadioButton.stories.tsx
Labels: canary, Version: Minor
