Repository artsy/palette-mobile, pull requests merged in 2024-05, with the labels that each got.

#225 feat: support placeholders in Input
  src/elements/Input/Input.tsx
Labels: Version: Minor

#226 feat: move follow button func to palette
  src/elements/Button/FollowButton.tsx
  src/elements/ButtonNew/Button.stories.tsx
  src/elements/ButtonNew/FollowButton.tsx
  src/utils/formatLargeNumber.ts
  src/utils/formatLargeNumbers.tests.ts
Labels: Jira Synced, canary, Version: Minor

#227 chore: add support to children in message component
  src/elements/Message/Message.stories.tsx
  src/elements/Message/Message.tsx
Labels: Version: Minor, Squash On Green

#228 chore: update commit author to shared account #trivial
  .autorc
Labels: Jira Synced, Version: Minor

#229 fix: loading state to FollowButton, hides checkmark when loading
  src/elements/Button/FollowButton.tsx
  src/elements/ButtonNew/FollowButton.tsx
Labels: Version: Minor
