Repository artsy/palette-mobile, pull requests merged in 2024-09, with the labels that each got.

#249 feat(Button): swaps the current button by the new button using reanimated
  .storybook/storybook.requires.js
  src/elements/Button/Button.stories.tsx
  src/elements/Button/Button.tests.tsx
  src/elements/Button/Button.tsx
  src/elements/Button/FollowButton.tsx
  src/elements/Button/LinkButton.tsx
  src/elements/Button/colors.ts
  src/elements/Button/index.ts
  src/elements/Button/index.tsx
  src/elements/ButtonNew/Button.stories.tsx
  src/elements/ButtonNew/Button.tsx
  src/elements/ButtonNew/CTAButton.tsx
  src/elements/ButtonNew/FollowButton.tsx
  src/elements/ButtonNew/LinkButton.tsx
  src/elements/ButtonNew/colors.ts
Labels: Version: Minor

#250 build(deps): bumps react-native-reanimated from 3.3.0 to 3.6.3
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Jira Synced, canary, Version: Major

#251 feat: Add TrendingIcon
  src/svgs/TrendingIcon.tsx
  src/svgs/index.tsx
Labels: Version: Minor, Squash On Green

#253 refactor(Button): enable loading state for button
  src/elements/Button/Button.stories.tsx
  src/elements/Button/Button.tsx
  src/elements/Button/FollowButton.tsx
  src/elements/Button/colors.ts
Labels: Version: Minor

#260 build(deps): bump reanimated from 3.3.0 to 3.8.1
  ios/Podfile.lock
  package.json
  src/elements/Screen/ScreenFlatList.tsx
  yarn.lock
Labels: canary, Version: Minor

#252 build(deps): bump react-native from 0.72.12 to 0.73.9
  Gemfile
  Gemfile.lock
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/debug/java/com/palettemobile/ReactNativeFlipper.java
  android/app/src/main/java/com/palettemobile/MainActivity.java
  android/app/src/main/java/com/palettemobile/MainActivity.kt
  android/app/src/main/java/com/palettemobile/MainApplication.java
  android/app/src/main/java/com/palettemobile/MainApplication.kt
  android/app/src/release/java/com/palettemobile/ReactNativeFlipper.java
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  babel.config.js
  ios/PaletteMobile.xcodeproj/project.pbxproj
  ios/PaletteMobile/AppDelegate.mm
  ios/PaletteMobile/Info.plist
  ios/PaletteMobile/PrivacyInfo.xcprivacy
  ios/Podfile
  ios/Podfile.lock
  package.json
  tsconfig.json
  yarn.lock
Labels: Jira Synced, Version: Minor, post-react-conf-updates

#261 chore: remove tsappconfig and toggle noemit
  tsconfig.app.json
  tsconfig.json
Labels: Version: Minor

#262 feat(dev): Add pull-lock to Palette Mobile
  .husky/post-merge
  .vscode/settings.json
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Version: Minor
