Repository artsy/palette-mobile, pull requests merged in 2024-04, with the labels that each got.

#211 Increase zIndex for the ToolTip component
  src/elements/ToolTip/ToolTipFlyout.tsx
Labels: Version: Minor, Squash On Green

#212 feat(AMBER-342): Adds HideIcon
  src/svgs/HideIcon.tsx
  src/svgs/index.tsx
Labels: Jira Synced, Version: Minor

#213 feat(DIA-558): add personIcon and multiplePersonsIcon
  src/svgs/MultiplePersonsIcon.tsx
  src/svgs/PersonIcon.tsx
  src/svgs/index.tsx
Labels: Jira Synced, Version: Minor

#214 feat(DIA-558): add verified person and shield filled icons
  src/svgs/ShieldFilledIcon.tsx
  src/svgs/VerifiedPersonIcon.tsx
  src/svgs/index.tsx
Labels: Jira Synced, Version: Minor

#215 fix(APPL-872): return null if Collapse is not opened
  src/elements/Collapse/Collapse.tsx
Labels: Jira Synced, Version: Minor

#216 feat(a11y): Add accessibility label on popover
  src/elements/Popover/Popover.tsx
Labels: Version: Minor

#217 chore: upgrade rn to latest minor version
  package.json
  yarn.lock
Labels: squashongreen, Version: Minor

#218 fix: rn followups - pod install
  ios/Podfile.lock
Labels: squashongreen, Version: Minor, Squash On Green

#220 build(package.json): fixes package json repo property
  package.json
Labels: canary, Version: Minor

#221 feat(entityheader): add theme support
  src/elements/EntityHeader/EntityHeader.tsx
Labels: Version: Minor

#222 fix(ci): Fix missing .allcontributorsrc file for auto.rc
  .all-contributorsrc
  CONTRIBUTORS.md
Labels: minor

#223 fix(ci): Remove all contributors
  .all-contributorsrc
  .autorc
  CONTRIBUTORS.md
Labels: Version: Minor

#224 fix: remove unnecessary console.log from EntityHeader
  src/elements/EntityHeader/EntityHeader.tsx
Labels: Version: Patch
