Repository artsy/palette-mobile, pull requests merged in 2024-01, with the labels that each got.

#172 feat: Update Banner Component
  .storybook/storybook.requires.js
  src/elements/Banner/Banner.stories.tsx
  src/elements/Banner/Banner.tsx
Labels: Version: Minor

#176 chore: support animated sticky sub header
  src/elements/Screen/Screen.stories.tsx
  src/elements/Screen/StickySubHeader.tsx
  src/elements/Screen/index.tsx
Labels: Version: Minor

#175 build(deps): bump react-native from 0.70.14 to 0.72.10
  .circleci/config.yml
  .eslintrc.js
  .gitignore
  .nvmrc
  .tool-versions
  .vscode/settings.json
  Gemfile
  Gemfile.lock
  android/app/build.gradle
  android/app/build_defs.bzl
  android/app/src/debug/java/com/palettemobile/ReactNativeFlipper.java
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/palettemobile/MainActivity.java
  android/app/src/main/java/com/palettemobile/MainApplication.java
  android/app/src/main/java/com/palettemobile/newarchitecture/MainApplicationReactNativeHost.java
  android/app/src/main/java/com/palettemobile/newarchitecture/components/MainComponentsRegistry.java
  android/app/src/main/java/com/palettemobile/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  android/app/src/main/jni/CMakeLists.txt
  android/app/src/main/jni/MainApplicationModuleProvider.cpp
  android/app/src/main/jni/MainApplicationModuleProvider.h
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
  android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h
  android/app/src/main/jni/MainComponentsRegistry.cpp
  android/app/src/main/jni/MainComponentsRegistry.h
  android/app/src/main/jni/OnLoad.cpp
  android/app/src/main/res/drawable/rn_edit_text_material.xml
  android/app/src/release/java/com/palettemobile/ReactNativeFlipper.java
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle
  ios/PaletteMobile.xcodeproj/project.pbxproj
  ios/PaletteMobile/AppDelegate.h
  ios/PaletteMobile/AppDelegate.mm
  ios/PaletteMobile/Info.plist
  ios/Podfile
  ios/Podfile.lock
  metro.config.js
  package.json
  src/elements/Checkbox/Checkbox.tsx
  src/elements/LegacyScreen/LegacyScreen.tsx
  src/elements/ProgressBar/ProgressBar.tsx
  src/elements/Radio/RadioButton.tsx
  src/elements/Screen/ScreenScrollContext.tsx
  src/elements/Tabs/SubTabBar.tsx
  yarn.lock
Labels: Jira Synced, canary, squashongreen, Version: Major, hackathon

#177 feat: support listening for screen events
  src/elements/Screen/index.tsx
Labels: Version: Minor

#178 feat: support dynamic height for sticky tabs
  src/elements/Screen/StickySubHeader.tsx
Labels: squashongreen, Version: Minor

#179 build(deps): bump react-native-svg from 13.7.0 to .14.1.0
  ios/PaletteMobile.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Version: Minor
