Repository artsy/palette-mobile, pull requests merged in 2024-02, with the labels that each got.

#181 feat(constants): Add global opacity setter
  src/constants.ts
  src/elements/Touchable/Touchable.tsx
Labels: Version: Minor

#182 fix(tabs): Ensure tabs use default active opacity
  src/elements/Tabs/TabsContainer.tsx
Labels: Version: Patch

#183 feat(tabs): Update type to allow title to render jsx
  src/elements/Screen/Header.tsx
  src/elements/Tabs/TabsWithHeader.tsx
Labels: Version: Minor

#180 feat(avatar): Fade in on load
  src/elements/Avatar/Avatar.tsx
Labels: canary, minor, Version: Minor

#184 feat: support gap columnGap and rowGap in Box, Flex
  src/elements/Box/Box.stories.tsx
  src/elements/Box/Box.tsx
Labels: Version: Minor, FF

#185 fix(tabs): Fix padding on large title
  src/elements/Tabs/TabsWithHeader.tsx
Labels: Version: Minor

#187 fix: disable width calculation if no long text is specified
  src/elements/Button/Button.tsx
Labels: Jira Synced, Version: Minor

#186 feat: add Screen.LazyScrollContext
  src/elements/Image/Image.tsx
  src/elements/LazyFlatlist/LazyFlatlist.tsx
  src/elements/LazyFlatlist/index.tsx
  src/elements/LazyFlatlist/useHasSeenItem.tsx
  src/elements/index.tsx
Labels: Version: Minor

#188 chore: Screen header improvements
  src/elements/Screen/Header.tsx
  src/elements/Screen/StickySubHeader.tsx
Labels: canary, Version: Minor

#189 fix: content jump after switching tabs
  src/elements/LazyFlatlist/useHasSeenItem.tsx
  src/elements/Screen/StickySubHeader.tsx
Labels: Version: Minor

#190 fix: title centering when no right element is present
  src/elements/Screen/Header.tsx
Labels: Version: Minor

#191 fix: opacity animation in android
  src/elements/Screen/StickySubHeader.tsx
Labels: squashongreen, Version: Minor

#173 feat(h13): Add BlurHash to Image
  ios/Podfile.lock
  package.json
  src/elements/Image/Image.stories.tsx
  src/elements/Image/Image.tsx
  yarn.lock
Labels: canary, Version: Minor, hackathon

#196 chore: Add Android app icon
  android/app/src/main/ic_launcher-playstore.png
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  android/app/src/main/res/values/ic_launcher_background.xml
Labels: Version: Minor

#197 feat: Add Switch component
  .storybook/storybook.requires.js
  src/elements/Switch/Switch.stories.tsx
  src/elements/Switch/Switch.tsx
  src/elements/Switch/index.tsx
Labels: Jira Synced, Version: Minor
