Repository artsy/palette-mobile, pull requests merged in 2024-06, with the labels that each got.

#232 chore: allow disabling keyboard avoidance
  src/elements/Screen/Body.tsx
Labels: Version: Minor

#233 chore(Body): do not inject styles in Fragment component
  src/elements/Screen/Body.tsx
Labels: Version: Minor

#234 chore: add iconsize prop
  src/elements/BackButton/BackButton.tsx
Labels: Version: Minor

#235 chore: support progressBarStyle for ProgressBar component
  src/elements/ProgressBar/ProgressBar.tsx
Labels: Version: Minor

#236 chore: support text variants for radio button
  src/elements/Radio/RadioButton.tsx
Labels: Version: Minor

#237 chore: update @artsy/palette-tokens
  package.json
  yarn.lock
Labels: squashongreen, Version: Minor

#238 fix: checkbox subtitle text color
  src/elements/Checkbox/Checkbox.tsx
Labels: Version: Minor

#239 chore: support innerRef inside Screen.Flatlist
  src/elements/Screen/ScreenFlatList.tsx
Labels: Jira Synced, Version: Minor

#240 feat: support masks
  src/elements/Input/Input.tsx
  src/elements/Input/maskValue.tests.ts
  src/elements/Input/maskValue.ts
Labels: Version: Minor

#241 fix(Input): proper typing and initial state
  src/elements/Input/Input.tsx
  src/elements/Input/maskValue.ts
Labels: squashongreen, Version: Minor

#242 build(deps-CI): update macOS orb to version 2.5.1
  .circleci/config.yml
Labels: Jira Synced, Version: Minor
