Repository artsy/palette-mobile, pull requests merged in 2024-12, with the labels that each got.

#292 chore: make post-merge hook executable #trivial
  .husky/post-merge
Labels: squashongreen, Version: Minor

#295 feat: allow VisualClue color to be customized
  src/elements/VisualClue/VisualClue.stories.tsx
  src/elements/VisualClue/VisualClueDot.tsx
  yarn.lock
Labels: Jira Synced, Version: Minor, Squash On Green

#296 feat: add a11y to checkbox + testid
  src/elements/Checkbox/Check.tsx
Labels: Squash On Green
