Repository artsy/palette-mobile, pull requests merged in 2025-09, with the labels that each got.

#374 fix(perf): replace reanimated opacity animation with rn animated
  src/elements/Image/Image.tsx
Labels: Jira Synced, Version: Minor

#379 fix: ref type for react 19
  src/elements/Tabs/TabMasonry.tsx
Labels: Jira Synced, Version: Minor

#386 build(deps): remove unused dependencies and use expo ts config extension
  Gemfile
  Gemfile.lock
  babel.config.js
  package.json
  src/animation/CssTransition.tsx
  tsconfig.json
  yarn.lock
Labels: Jira Synced, canary, Version: Minor

#388 chore: align fast image version on palette-mobile with eigen
  package.json
  yarn.lock
Labels: Version: Minor

#387 build(deps): migrate to yarn 4
  .circleci/config.yml
  .gitignore
  .tool-versions
  .yarn/releases/yarn-4.10.0.cjs
  .yarnrc.yml
  README.md
  package.json
  yarn.lock
Labels: Jira Synced, Version: Minor

#389 fix: performance issues on skeleton image
  src/elements/Skeleton/Skeleton.tsx
Labels: Version: Minor

#390 chore: upgrade reanimated to 3.19.1
  package.json
  src/elements/Input/Input.tests.tsx
  src/setupJest.ts
  yarn.lock
Labels: Version: Minor, Squash On Green
