Repository artsy/palette-mobile, pull requests merged in 2025-04, with the labels that each got.

#324 build(deps): bump react-native from 0.75.4 to 0.76.7
  Gemfile
  Gemfile.lock
  android/app/src/main/java/com/palettemobile/MainApplication.kt
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  ios/PaletteMobile.xcodeproj/project.pbxproj
  ios/PaletteMobile/PrivacyInfo.xcprivacy
  ios/Podfile.lock
  package.json
  src/setupJest.ts
  yarn.lock
Labels: Jira Synced, canary, Version: Major

#326 build(deps): bump react-native from 0.76.7 to 0.76.9
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: squashongreen, Version: Minor

#327 feat: improve scroll and performance on Screen.Flatlist
  src/elements/Screen/Header.tsx
  src/elements/Screen/ScreenScrollContext.tsx
  src/elements/Screen/StickySubHeader.tsx
  src/elements/Screen/hooks/useListenForScreenScroll.tsx
  src/elements/Screen/hooks/useShowLargeTitle.ts
Labels: Jira Synced, canary, Version: Minor

#325 fix: Increase dark mode onBackgroundMedium to increase contrast
  src/tokens.ts
Labels: Version: Minor

#328 chore: update radio button component
  src/elements/Radio/RadioButton.tsx
Labels: squashongreen, Version: Minor

#329 chore: Upgrade @artsy/palette-tokens to 6.5.0
  package.json
  yarn.lock
Labels: Version: Minor, Squash On Green

#330 fix: Increase contrast for onBackgroundMedium dark theme color
  src/tokens.ts
Labels: Version: Minor

#333 chore: remove duplicate auto-release plugins
  .autorc
Labels: Version: Minor

#334 fix: chevron icon component
  src/svgs/ChevronIcon.tsx
Labels: Jira Synced, squashongreen, Version: Minor

#335 fix: Info message component contrast ratio
  src/elements/Message/Message.tsx
Labels: Jira Synced, Version: Minor

#340 feat: support pill tabs
  src/elements/Tabs/TabsContainer.tsx
Labels: Jira Synced, Version: Minor

#341 chore: better accessibility for pills
  src/elements/Pill/Pill.tsx
Labels: Version: Minor, Accessibility

#342 fix: accessibility issues on search input
  src/elements/SearchInput/RoundSearchInput.tsx
Labels: Version: Minor, Accessibility

#343 chore: remove figma link from palette
  src/tokens.ts
Labels: Version: Minor
