Repository artsy/palette-mobile, pull requests merged in 2025-03, with the labels that each got.

#314 feat: Add onOpenComplete callback to Popover
  src/elements/Popover/Popover.tsx
Labels: Version: Minor

#315 fix: Replace TouchableHighlight with TouchableOpacity in Touchable
  src/elements/Touchable/Touchable.tsx
Labels: Jira Synced, Version: Minor

#316 feat(ONYX-1606): add largeTitle prop to StickySubHeader
  src/elements/Screen/Screen.stories.tsx
  src/elements/Screen/StickySubHeader.tsx
Labels: Jira Synced, Version: Minor

#317 build(deps): bump flashlist to latest
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: canary, FF, Squash On Green

#319 fix: remove skeleton text on android devices
  src/elements/Skeleton/Skeleton.tsx
Labels: Jira Synced, Version: Minor

#320 feat: add radio button block variant
  src/elements/Radio/RadioButton.stories.tsx
  src/elements/Radio/RadioButton.tsx
  src/elements/Radio/RadioDot.tsx
Labels: Version: Minor, Squash On Green

#322 chore: fix issue with radio button
  scripts/flip-table-soft
  src/elements/Radio/RadioButton.stories.tsx
  src/elements/Radio/RadioButton.tsx
Labels: Version: Minor, Squash On Green

#323 feat: add sort icon
  src/svgs/SortIcon.tsx
  src/svgs/index.tsx
Labels: Version: Minor
