Repository artsy/palette-mobile, pull requests merged in 2025-10, with the labels that each got.

#393 chore: upgrade storybook to v7
  .storybook/Storybook.tsx
  .storybook/main.js
  .storybook/preview.jsx
  .storybook/storybook.requires.js
  app/App.tsx
  metro.config.js
  package.json
  src/elements/CollapsibleMenuItem/CollapsibleMenuItem.stories.tsx
  src/elements/Dialog/Dialog.stories.tsx
  src/elements/Image/Image.stories.tsx
  src/elements/Input/Input.stories.tsx
  src/elements/List/List.stories.tsx
  src/elements/Message/Message.stories.tsx
  src/elements/Pill/Pill.stories.tsx
  src/elements/Popover/Popover.stories.tsx
  src/elements/ProgressBar/ProgressBar.stories.tsx
  src/elements/Radio/RadioButton.stories.tsx
  src/elements/Screen/Screen.stories.tsx
  src/elements/Tabs/Tabs.stories.tsx
  src/elements/Text/Text.stories.tsx
  src/elements/ToolTip/ToolTip.stories.tsx
  src/elements/VisualClue/VisualClue.stories.tsx
  src/storybook/decorators.tsx
  yarn.lock
Labels: Jira Synced, Version: Minor

#395 fix: large button cropped
  src/elements/Button/Button.tsx
  src/elements/ButtonNew/Button.tsx
Labels: Jira Synced, Version: Minor, Squash On Green

#396 fix: remove jotai and refactor to use useState in order to fix palette-mobile
  package.json
  src/storybook/decorators.tsx
  yarn.lock
Labels: Version: Minor
