Repository artsy/palette-mobile, pull requests merged in 2025-06, with the labels that each got.

#353 build(deps): bump safe area view
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Version: Minor

#356 chore: export image skeleton
  ios/Podfile.lock
  package.json
  src/elements/Image/Image.tsx
  src/setupJest.ts
  yarn.lock
Labels: Version: Minor, Squash On Green

#355 build(deps): react native testing lib to latest
  package.json
  src/setupJest.ts
  yarn.lock
Labels: Version: Minor, FF

#360 chore: add hide screen to TabsWithHeader
  src/elements/Tabs/TabsWithHeader.tsx
Labels: Version: Minor

#361 chore: update CircleCI orbs and Xcode version to match eigen
  .circleci/config.yml
Labels: Version: Minor, FF
