Repository artsy/palette-mobile, pull requests merged in 2025-05, with the labels that each got.

#344 chore: increase debounce focued tab duration
  src/elements/Tabs/TabsContainer.tsx
Labels: Version: Minor, Squash On Green

#345 feat: add accessibility roles and labels to various components for improved a11y
  .eslintrc.js
  package.json
  src/elements/BackButton/BackButton.tsx
  src/elements/Banner/Banner.tsx
  src/elements/Button/Button.tsx
  src/elements/Button/LinkButton.tsx
  src/elements/ButtonNew/Button.tsx
  src/elements/ButtonNew/LinkButton.tsx
  src/elements/Checkbox/Checkbox.tsx
  src/elements/Chip/Chip.tsx
  src/elements/CollapsibleMenuItem/CollapsibleMenuItem.tsx
  src/elements/Dialog/Dialog.tsx
  src/elements/Input/Input.tests.tsx
  src/elements/Input/Input.tsx
  src/elements/LegacyScreen/LegacyScreen.tsx
  src/elements/LegacyTabs/StepTabs.tsx
  src/elements/LegacyTabs/Tab.tsx
  src/elements/MenuItem/MenuItem.tsx
  src/elements/Message/Message.tsx
  src/elements/Radio/RadioButton.tsx
  src/elements/Screen/Header.tsx
  src/elements/SearchInput/RoundSearchInput.tsx
  src/elements/ToolTip/ToolTipFlyout.tsx
  src/elements/Touchable/Touchable.stories.tsx
  yarn.lock
Labels: Jira Synced, Version: Minor

#346 feat(a11y): improve checkbox, radiobutton, linkText a11y
  src/elements/Checkbox/Checkbox.tsx
  src/elements/Radio/RadioButton.tsx
  src/elements/Text/LinkText.tsx
Labels: Jira Synced, Version: Minor

#347 fix: checkbox issue with children
  src/elements/Checkbox/Checkbox.tsx
Labels: Jira Synced, Version: Minor

#348 fix: show only selected tab instead of tab transition
  src/elements/Tabs/TabsContainer.tsx
Labels: Jira Synced, Version: Minor

#351 feat: add selected a11y state to radioButton
  src/elements/Radio/RadioButton.tsx
Labels: Version: Minor, FF
