Repository artsy/palette-mobile, pull requests merged in 2025-02, with the labels that each got.

#301 feat: adding new ArrowBackIcon
  src/svgs/ArrowBackIcon.tsx
  src/svgs/index.tsx
Labels: Version: Minor

#302 fix: entity header ellipsizeMode
  src/elements/EntityHeader/EntityHeader.tsx
Labels: Jira Synced, Version: Minor

#303 docs(home view): add a link to Notion docs
  README.md
Labels: Version: Minor

#304 chore: upgrade reanimated version
  .tool-versions
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Version: Minor

#305 fix: dark-mode for inputs
  src/elements/Input/Input.tsx
  src/elements/Input/helpers.ts
Labels: canary, Version: Minor

#306 fix: default color for inputs
  src/elements/Input/helpers.ts
Labels: Version: Minor, Squash On Green

#307 chore: fix dark mode tokens
  src/tokens.ts
Labels: Version: Minor

#309 chore: more dark mode fixes
  src/elements/Screen/Body.tsx
  src/elements/Text/LinkText.tsx
Labels: Version: Minor

#311 fix: popovers on dark mode
  src/elements/Popover/Popover.tsx
Labels: Version: Minor
